name: Development

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses : actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: yarn

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get AWS Account ID
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "AWS_ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

    - name: Use AWS Account ID
      run: echo "AWS Account ID is $AWS_ACCOUNT_ID"

    - name: Install AWS CDK
      run: npm i -g aws-cdk

    - name: CDK synthetize
      run: cdk synth

    - name: Deploy CDK Stack
      run: cdk deploy --require-approval never